# Generated by Django 2.1.2 on 2019-03-28 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('javasikhoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='topics',
            name='Link',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='topics',
            name='Sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='javasikhoApp.Lang'),
        ),
    ]
